package main

import "fmt"

func main() {
	process()
	fmt.Println("This will be printed only if the panic was recovered inside process")
}

func process() {

	// immediately executing function but since we used defer, it will run at the end
	// comment below function to see what happens if recovery is not there
	defer func() {
		r := recover()
		if r != nil {
			fmt.Println("Recovered:", r)
		}
	}()

	fmt.Println("Start process")
	panic("Something went wrong")
	// fmt.Println("End process")
}
